files:
  - source: /docs/**/*.md
    ignore:
      - /**/extras
      - /**/navbar.md
      - /**/assets/
      - /**/files/
    translation: /translations/%locale_with_underscore%/%original_path%/%original_file_name%
